### ISSUE TITLE
please reopen if still problems

### ISSUE THREAD

**Issue by 19joho66** [frescobaldi/python-poppler-qt5#32]
please reopen if still problems

_Originally posted by @wbsoft in https://github.com/frescobaldi/python-poppler-qt5/issues/24#issuecomment-532736504_

I still get the error

sip Poppler::LinkRendition is undefined

when I try to build on windows

**Comment by wbsoft** [comment]
Do you use current master? Which version of poppler are you using?

**Comment by 19joho66** [comment]
I'm using version 0.74 and I've build poppler based on version 0.82

**Comment by wbsoft** [comment]
Please try current master from git, which is at 0.75.0

**Comment by 19joho66** [comment]
Ok, I can build with that version on windows now. Thanks
